### ISSUE TITLE
hello can the -ck patches for the kernel 5.3 be included in this awesome patch's set ?

### ISSUE THREAD

**Issue by javashin** [sirlucjan/linux-lucjan#2]
hi lucjan i use your patches for all my kernel compilations , i compile my kernel with your patch as base for my own custom compilation with clang , i reversed the BMQ scheduler of ur patch and i patched -ck into it , added the gentoo patches (genpatches) , and i inject ZFS built-in to compile inside the kernel i been doing this for a few months now is nice to have someone who make a mega patch with all the goodies from the best sources , -pf , -zen , clear linux , etc .

i found a problem with BMQ https://gitlab.com/alfredchen/linux-bmq/issues/4  & https://gitlab.com/alfredchen/bmq/issues/9 , on my system that makes a lot of lagging and hangs when i compile with -j3 + LTO and at the same time watching videos on youtube or mpv . i found the source of the problem , and was a service tool that make auto Re-nice all the time (ananicy)  , this dont happen with CFS scheduler , and i was using your patches with bmq just disabled but today -ck patches from con kolivas got out -zen Zen-Sources kernel added this patches already into their kernel patch set , and i discovered the Best Result ever , no hangs no lagging in the same situation compiling with -j3 and LTO. so what do u think is just a suggestion a lot of other people have problems with BMQ lately . like this problem . until this get fixed im going to be reversing bmq out ur patches and replacing it with MuQSS scheduler , or maybe u can get around all this and include both bmq and MuQSS all together inside ur mega patch :) , nice work , thanks in advance.

**Comment by javashin** [comment]
![Screenshot_2019-10-25_23-03-07](https://user-images.githubusercontent.com/15115613/67613515-74da9c00-f77c-11e9-8d8f-9ed0e5439e4c.png)
![Screenshot_2019-10-25_23-07-39](https://user-images.githubusercontent.com/15115613/67613516-74da9c00-f77c-11e9-8409-752c78d93e32.png)

**Comment by sirlucjan** [comment]
Unfortunately, it is not possible to impose BMQ and MUQSS at the same time. You have to choose one of these solutions. In my case BMQ works better and that's why I chose it as my default CPU scheduler. Greetings and thank you for using my patchset.

**Comment by javashin** [comment]
Cool My friend :)
