### ISSUE TITLE
bfq is not enabled by default when compiling with CONFIG_MQ_IOSCHED_DEADLINE=y

### ISSUE THREAD

**Issue by zhmars** [sirlucjan/linux-lucjan#3]
Hi, thanks for the patchset.

The `0002-LL-elevator-set-default-scheduler-to-bfq-for-blk-mq.patch` seems not work anymore. To enable bfq, I have to config my udev rule.

Running on linux 5.7.7 with 5.7-lucjan-ll32.

**Comment by sirlucjan** [comment]
Hello and thank you for using my patch.

Unfortunately, I can't confirm that issue. I've compiled the latest version of kernel with patch ll32 and my default I/O scheduler is BFQ.  

```
lucjan@archlinux ~ $ cat /sys/block/sda/queue/scheduler
[bfq] none
lucjan@archlinux ~ $ uname -a
Linux archlinux 5.7.7.ll32-1-lucjan-git #1 SMP PREEMPT Thu, 02 Jul 2020 02:51:14 +0000 x86_64 GNU/Linux
```
Below is a full record of the logs of the options I am interested in: 

```
CONFIG_LL_BRANDING=y
CONFIG_MHASWELL=y
[bfq] none
Linux version 5.7.7.ll32-1-lucjan-git (linux-lucjan-git@archlinux) (gcc version 10.1.0 (GCC), GNU ld (GNU Binutils) 2.34.0) #1 SMP PREEMPT Thu, 02 Jul 2020 02:51:14 +0000
Linux archlinux 5.7.7.ll32-1-lucjan-git #1 SMP PREEMPT Thu, 02 Jul 2020 02:51:14 +0000 x86_64 GNU/Linux
[    0.097068] sched/bmq: BMQ CPU Scheduler 5.7-r2 by Alfred Chen.
[    0.097116] rcu: RCU calculated value of scheduler-enlistment delay is 100 jiffies.
[    0.484119] io scheduler bfq registered
[    0.484120] BFQ-dev I/O-scheduler: v11 (with cgroups support)
[    0.653033] UKSM: relative memcmp_cost = 215 hash=3453574821 cmp_ret=0.
```
I do not use any udev rules to manage my drives except hdparm (https://wiki.archlinux.org/index.php/Hdparm):
```
lucjan@archlinux ~ $ ls /etc/udev/rules.d
50-hdparm.rules
```

Moreover, the patch you mentioned - 0002-LL-elevator-set-default-scheduler-to-bfq-for-blk-mq.patch - is included in the BFQ-dev as: https://github.com/sirlucjan/bfq-mq-lucjan/commit/7a11cb37cdd54eca17b52850f0f34ad8db61a38b and this is one of the changes I make to the original BFQ-dev.

Anyway, as you can see, I can't reproduce your error. You'd have to give me the following information to help: 

- what operating system you are using

- on which config you compile

- if this has happened before and if you've used a patch before

Only then will I be able to help.

**Comment by juliagoda** [comment]
I can confirm the issue doesn't appear in my case

```
[juliagoda@juliagoda ~]$ cat /sys/block/sda/queue/scheduler
[bfq] none
[juliagoda@juliagoda ~]$ uname -a
Linux juliagoda 5.7.7.ll32-1-juliagoda-git #1 SMP PREEMPT Wed, 01 Jul 2020 15:26:26 +0000 x86_64 GNU/Linux
```

**Comment by zhmars** [comment]
Thanks for the comments.

- what operating system you are using

  Arch Linux

- on which config you compile

```conf
CONFIG_LL_BRANDING=y
# CONFIG_SCHED_ALT is not set

CONFIG_MQ_IOSCHED_DEADLINE=y
# CONFIG_MQ_IOSCHED_KYBER is not set
CONFIG_IOSCHED_BFQ=y
CONFIG_BFQ_GROUP_IOSCHED=y
# CONFIG_BFQ_CGROUP_DEBUG is not set
```

```sh
# dmesg | grep -i bfq
[    0.284007] io scheduler bfq registered
[    0.284008] BFQ-dev I/O-scheduler: v11 (with cgroups support)

# cat /sys/block/sda/queue/scheduler
[mq-deadline] bfq none
```

- if this has happened before and if you've used a patch before

Hmm, It worked as expected when the patch was introduced at first time and I didn't check it after that. I noticed this issue after upgrading to linux 5.7.y.

I thought there maybe something wrong with my config. Sorry for the noise.

**Comment by zhmars** [comment]
Hi, I just rebuilt the kernel without `CONFIG_MQ_IOSCHED_DEADLINE=y` and now bfq is enabled by default. I also noticed both of you have disabled `CONFIG_MQ_IOSCHED_DEADLINE` option in your kernel config. Right?

Not quite sure, maybe this issue only occur when `CONFIG_MQ_IOSCHED_DEADLINE` is enabled?

**Comment by sirlucjan** [comment]
Yes, I'm disabling MQ_DEADLINE. I'll have to take a look at it in my spare time. I've never compiled a kernel with this scheduler.

**Comment by sirlucjan** [comment]
I tried to do something quick. Could you check? I doubt it will work and I'm probably going to have to dig deeper but it won't hurt to try.

**Comment by zhmars** [comment]
> I tried to do something quick. Could you check? I doubt it will work and I'm probably going to have to dig deeper but it won't hurt to try.

Hi, I tried patch ll34 with no luck. `mq-deadline` is still the default I/O scheduler.

Just for note, zen kernel has similar changes, see https://github.com/zen-kernel/zen-kernel/commit/93772b70b657d208db3108d6216b077a424e9869. And it works as expected. 
Testing on linux-zen 5.7.7.zen1-1 from arch repo.

**Comment by sirlucjan** [comment]
So try it now - I've made the same changes.

**Comment by zhmars** [comment]
Patch ll37, same as previous.

**Comment by sirlucjan** [comment]
Did you use my new config? Did you enable mq_deadline_nodefault? I've added patch from zen-kernel.

**Comment by zhmars** [comment]
> Did you use my new config? Did you enable mq_deadline_nodefault? I've added patch from zen-kernel.

Yes, I use your new config but not enable `CONFIG_MQ_IOSCHED_DEADLINE_NODEFAULT `.

```
CONFIG_LL_BRANDING=y

CONFIG_MQ_IOSCHED_DEADLINE=y
# CONFIG_MQ_IOSCHED_DEADLINE_NODEFAULT is not set
# CONFIG_MQ_IOSCHED_KYBER is not set
CONFIG_IOSCHED_BFQ=y
CONFIG_BFQ_GROUP_IOSCHED=y
# CONFIG_BFQ_CGROUP_DEBUG is not set
```

**Comment by sirlucjan** [comment]
Could you enable it?

**Comment by zhmars** [comment]
I just enabled it and rebuilt the kernel, but it made no difference.

```
CONFIG_LL_BRANDING=y

CONFIG_MQ_IOSCHED_DEADLINE=y
CONFIG_MQ_IOSCHED_DEADLINE_NODEFAULT=y
# CONFIG_MQ_IOSCHED_KYBER is not set
CONFIG_IOSCHED_BFQ=y
CONFIG_BFQ_GROUP_IOSCHED=y
# CONFIG_BFQ_CGROUP_DEBUG is not set
```

```sh
# dmesg | grep 'io scheduler'
[    0.284501] io scheduler mq-deadline-nodefault registered
[    0.284522] io scheduler bfq registered

# cat /sys/block/sda/queue/scheduler
[mq-deadline-nodefault] bfq none
```

**Comment by sirlucjan** [comment]
I've made some minor changes, and this time I'll test it at home. Until I have to see for myself why it doesn't work. Tomorrow I'll let you know about the results because on my computer the compilation takes some time.

**Comment by sirlucjan** [comment]
I probably found a solution. Look at the result:

```
lucjan@archlinux ~ $ dmesg | grep -i mq-deadline
[    0.485063] io scheduler mq-deadline registered
lucjan@archlinux ~ $ dmesg | grep -i bfq
[    0.485086] io scheduler bfq registered
[    0.485086] BFQ-dev I/O-scheduler: v11 (with cgroups support)
lucjan@archlinux ~ $ cat /sys/block/sda/queue/scheduler
mq-deadline [bfq] none
lucjan@archlinux ~ $ uname -a
Linux archlinux 5.7.7.ll38-1-lucjan-git #1 SMP PREEMPT Sat, 04 Jul 2020 20:30:15 +0000 x86_64 GNU/Linux
lucjan@archlinux ~ $ ls /etc/udev/rules.d
50-hdparm.rules
```

Fragment of the config file:

```
#
# IO Schedulers
#
CONFIG_MQ_IOSCHED_DEADLINE=y
# CONFIG_MQ_IOSCHED_DEADLINE_NODEFAULT is not set
# CONFIG_MQ_IOSCHED_KYBER is not set
CONFIG_IOSCHED_BFQ=y
CONFIG_BFQ_GROUP_IOSCHED=y
# CONFIG_BFQ_CGROUP_DEBUG is not set
# end of IO Schedulers
```

On Sunday noon or afternoon, I'll put the ready-made solutions on the git, because it's a bit late now. Looks like the problem has been solved, but I'll wait for your insights.

**Comment by sirlucjan** [comment]
Could you try https://github.com/sirlucjan/linux-lucjan/commit/a2187639915331f432a79bb8ed562008a94161b6 ? It looks like patch 0002-LL-elevator-set-default-scheduler-to-bfq-for-blk-mq.patch is working properly and the culprit was the one I removed.  But we won't know the answer until you test it at home. It works for me, as you can see:

```
lucjan@archlinux ~ $ dmesg | grep -i mq-deadline
[    0.485063] io scheduler mq-deadline registered
lucjan@archlinux ~ $ dmesg | grep -i bfq
[    0.485086] io scheduler bfq registered
[    0.485086] BFQ-dev I/O-scheduler: v11 (with cgroups support)
lucjan@archlinux ~ $ cat /sys/block/sda/queue/scheduler
mq-deadline [bfq] none
lucjan@archlinux ~ $ uname -a
Linux archlinux 5.7.7.ll38-1-lucjan-git #1 SMP PREEMPT Sat, 04 Jul 2020 20:30:15 +0000 x86_64 GNU/Linux
lucjan@archlinux ~ $ ls /etc/udev/rules.d
50-hdparm.rules
lucjan@archlinux ~ $ cat /etc/udev/rules.d/50-hdparm.rules
ACTION=="add", SUBSYSTEM=="block", KERNEL=="sda", RUN+="/usr/bin/hdparm -B 255 -S 0 /dev/sda"
```

**Comment by zhmars** [comment]
Sorry for my late reply.

You are right. I can confirmed the patch ll38 fixed this issue. And now everything works as expected. Many thanks for your time and detailed explanation.

**Comment by sirlucjan** [comment]
Could you close issue?

**Comment by zhmars** [comment]
Closed. Thanks again.

**Comment by sirlucjan** [comment]
You're welcome. Thank you because you noticed a significant error - I don't compile mq_deadline and I had no idea that this removed patch is causing such problems.
